/* eslint-disable @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-assignment */
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useAppFunction } from '@dynatrace-sdk/react-hooks';
import { useNavigate } from 'react-router-dom';
import { Flex } from '@dynatrace/strato-components/layouts';
import { Heading, Paragraph } from '@dynatrace/strato-components/typography';
import type { Problem, ProblemsResponse } from '../types/problems';
import { downloadCioRcaPdf } from './RcaWorkbenchReport';
import './Home.css';

type RcaPreview = { problemId: string; analysis: string; nativeRootCauseEntity: string | null; occurrenceCount: number; managementZones?: string[]; problemFacts?: { title?: string; status?: string; severity?: string; category?: string; start?: string; end?: string; duration?: string; impactLevel?: string; affectedUsers?: string | number; affectedEntities?: string | number }; evidenceSummary: { correlatedEvents: number; incidentLogs: number; historicalOccurrences: number; timelineSnapshots: number } };
const upper = (value?: string) => (value ?? '').toUpperCase();
const formatTimestamp = (timestamp?: number) => timestamp ? new Intl.DateTimeFormat(undefined, { dateStyle: 'short', timeStyle: 'medium' }).format(new Date(timestamp)) : '—';
const formatDuration = (start?: number, end?: number) => { if (!start) return '—'; const ms = Math.max(0, (end && end > 0 ? end : Date.now()) - start); const mins = Math.floor(ms / 60000); const days = Math.floor(mins / 1440); const hours = Math.floor((mins % 1440) / 60); const rest = mins % 60; return days ? `${days}d ${hours}h` : hours ? `${hours}h ${rest}m` : `${rest}m`; };
const section = (analysis: string, title: string): string => { const lines = analysis.split(/\r?\n/); const index = lines.findIndex((line) => line.toLowerCase().includes(title.toLowerCase())); if (index < 0) return ''; const out: string[] = []; for (let i = index + 1; i < lines.length; i += 1) { if (/^\s*#{1,6}\s+/.test(lines[i])) break; if (lines[i].trim()) out.push(lines[i].trim()); } return out.join(' '); };
const confidence = (analysis: string): string => { const match = analysis.match(/confidence(?: level)?\s*[:\-]\s*([A-Za-z]+(?:\s*\/\s*[A-Za-z]+)?(?:\s*\(\s*\d+%\s*\))?)/i); return match?.[1] ?? 'Evidence based'; };
const speakProblem = (problem: Problem) => { if (!('speechSynthesis' in window)) return; window.speechSynthesis.cancel(); window.speechSynthesis.speak(new SpeechSynthesisUtterance(`Attention. New Dynatrace alert. ${problem.title || 'New problem alert'}.`)); };
export const Home = () => {
  const navigate = useNavigate(); const [selectedMz, setSelectedMz] = useState('ALL'); const [selectedProblem, setSelectedProblem] = useState<Problem | null>(null); const [rca, setRca] = useState<RcaPreview | null>(null); const [rcaBusy, setRcaBusy] = useState(false); const [rcaError, setRcaError] = useState(''); const [voiceEnabled, setVoiceEnabled] = useState(false); const [lastRefresh, setLastRefresh] = useState(Date.now()); const knownProblemIds = useRef(new Set<string>()); const initialised = useRef(false);
  const requestData = useMemo(() => ({ from: 'now-24h', to: 'now', pageSize: 100, ...(selectedMz !== 'ALL' ? { managementZoneId: selectedMz } : {}) }), [selectedMz]);
  const { data, isLoading, error, refetch } = useAppFunction<ProblemsResponse>({ name: 'getProblems', data: requestData }); const problems = useMemo(() => [...(data?.problems ?? [])].sort((a, b) => (b.startTime ?? 0) - (a.startTime ?? 0)), [data]);
  const zones = useMemo(() => { const map = new Map<string, string>(); for (const p of problems) for (const z of p.managementZones ?? []) if (z.id) map.set(z.id, z.name ?? z.id); return [...map.entries()].sort((a, b) => a[1].localeCompare(b[1])); }, [problems]);
  const openProblems = useMemo(() => problems.filter((p) => upper(p.status) === 'OPEN'), [problems]); const criticalHigh = useMemo(() => openProblems.filter((p) => ['CRITICAL', 'HIGH'].includes(upper(p.severityLevel))), [openProblems]); const aging = useMemo(() => openProblems.filter((p) => Boolean(p.startTime) && Date.now() - (p.startTime ?? 0) > 4 * 3600000), [openProblems]);
  useEffect(() => { const timer = window.setInterval(() => { void refetch(); setLastRefresh(Date.now()); }, 30000); return () => window.clearInterval(timer); }, [refetch]);
  useEffect(() => { if (!problems.length) return; if (!initialised.current) { problems.forEach((p) => { if (p.problemId) knownProblemIds.current.add(p.problemId); }); initialised.current = true; return; } const fresh = problems.find((p) => p.problemId && !knownProblemIds.current.has(p.problemId) && upper(p.status) === 'OPEN'); problems.forEach((p) => { if (p.problemId) knownProblemIds.current.add(p.problemId); }); if (fresh && voiceEnabled) speakProblem(fresh); }, [problems, voiceEnabled]);
  const detailQuery = useAppFunction<Problem>({ name: 'getProblemDetails', data: selectedProblem?.problemId ? { problemId: selectedProblem.problemId } : undefined }, { autoFetch: Boolean(selectedProblem?.problemId), autoFetchOnUpdate: Boolean(selectedProblem?.problemId) }); const detail = detailQuery.data ?? selectedProblem;
  const loadRca = useCallback(async (id: string) => { setRcaBusy(true); setRcaError(''); try { const response = await fetch('/api/analyzeProblemRca', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ problemId: id }) }); if (!response.ok) throw new Error(`RCA request failed with HTTP ${String(response.status)}`); const payload: unknown = await response.json(); if (!payload || typeof payload !== 'object' || Array.isArray(payload)) throw new Error('RCA response was empty or invalid.'); setRca(payload as RcaPreview); } catch (cause: unknown) { setRca(null); setRcaError(cause instanceof Error ? cause.message : 'Unable to generate RCA'); } finally { setRcaBusy(false); } }, []);
  useEffect(() => { if (selectedProblem?.problemId) { setRca(null); void loadRca(selectedProblem.problemId); } }, [selectedProblem?.problemId, loadRca]); const refresh = useCallback(() => { void refetch(); setLastRefresh(Date.now()); }, [refetch]);
  const enableVoice = () => { if ('speechSynthesis' in window) { window.speechSynthesis.cancel(); window.speechSynthesis.speak(new SpeechSynthesisUtterance('Dynatrace voice buzz enabled.')); setVoiceEnabled(true); } }; const disableVoice = () => { setVoiceEnabled(false); if ('speechSynthesis' in window) window.speechSynthesis.cancel(); }; const impacts = detail?.impactAnalysis?.impacts ?? [];
  return <Flex flexDirection="column" padding={0} gap={0}><main className="home-page"><div className="home-shell"><header className="home-header"><div><div className="home-brand">AXIS BANK <span>•</span> DYNATRACE OPERATIONS</div><div className="home-eyebrow">Problem Intelligence</div><h1>Live incident command center</h1><p>Detect the problem. Understand the impact. Generate the RCA — without leaving the incident view.</p></div><div className="home-toolbar"><span>Updated {new Date(lastRefresh).toLocaleTimeString()}</span><button type="button" onClick={refresh} disabled={isLoading}>↻ Refresh</button><button type="button" onClick={voiceEnabled ? disableVoice : enableVoice}>{voiceEnabled ? '🔊 Voice ON' : '🔇 Voice Buzz'}</button></div></header>
  <section className="home-filter"><div><label htmlFor="home-mz">Management Zone</label><select id="home-mz" value={selectedMz} onChange={(event) => setSelectedMz(event.target.value)}><option value="ALL">All Management Zones</option>{zones.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></div><div className="home-filter-note">Auto-refresh every 30 seconds · click any problem for live Davis RCA</div></section>
  {error && <div className="home-error">Unable to load Dynatrace problems. {error.message}</div>}
  <section className="home-kpis"><div><span>MATCHED</span><strong>{data?.totalCount ?? 0}</strong><small>last 24 hours</small></div><div><span>OPEN</span><strong>{openProblems.length}</strong><small>currently active</small></div><div><span>CRITICAL / HIGH</span><strong>{criticalHigh.length}</strong><small>priority incidents</small></div><div><span>AGING &gt; 4H</span><strong>{aging.length}</strong><small>needs attention</small></div></section>
  <section className="home-table-card"><div className="home-card-head"><div><div className="home-card-kicker">LIVE PROBLEM STREAM</div><h2>Active &amp; recent Dynatrace problems</h2></div><span>{problems.length} displayed</span></div><div className="home-table-wrap"><table><thead><tr><th>Started</th><th>Problem</th><th>Title</th><th>Severity</th><th>Impact</th><th>Status</th><th>Age</th><th>Management Zone</th></tr></thead><tbody>{isLoading && !problems.length ? <tr><td colSpan={8}>Loading live problems…</td></tr> : !problems.length ? <tr><td colSpan={8}>No problems found for the selected management zone.</td></tr> : problems.map((problem) => <tr key={problem.problemId ?? problem.displayId} onClick={() => setSelectedProblem(problem)}><td>{formatTimestamp(problem.startTime)}</td><td><b>{problem.displayId ?? problem.problemId ?? '—'}</b></td><td>{problem.title ?? '—'}</td><td><span className="home-pill">{problem.severityLevel ?? '—'}</span></td><td>{problem.impactLevel ?? '—'}</td><td>{problem.status ?? '—'}</td><td>{formatDuration(problem.startTime, problem.endTime)}</td><td>{(problem.managementZones ?? []).map((z) => z.name).filter(Boolean).join(', ') || '—'}</td></tr>)}</tbody></table></div></section>
  {selectedProblem && detail && <div className="home-overlay" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setSelectedProblem(null); }}><section className="home-modal" role="dialog" aria-modal="true" aria-label="Problem intelligence"><header><div><div className="home-card-kicker">INCIDENT INTELLIGENCE</div><h2>{detail.displayId ?? detail.problemId}</h2><p>{detail.title ?? 'Dynatrace Problem'}</p></div><div className="home-modal-actions"><button type="button" onClick={() => navigate(`/rca?problemId=${encodeURIComponent(detail.problemId ?? detail.displayId ?? '')}`)}>Open full RCA ↗</button><button type="button" className="home-close" onClick={() => setSelectedProblem(null)}>×</button></div></header><div className="home-modal-body"><div className="home-incident-strip"><div><span>STATUS</span><strong>{detail.status ?? '—'}</strong></div><div><span>SEVERITY</span><strong>{detail.severityLevel ?? '—'}</strong></div><div><span>IMPACT</span><strong>{detail.impactLevel ?? '—'}</strong></div><div><span>STARTED</span><strong>{formatTimestamp(detail.startTime)}</strong></div></div>
  <section className="home-rca-card"><div className="home-rca-head"><div><div className="home-card-kicker">DAVIS RCA</div><h3>Root cause &amp; incident assessment</h3></div>{rca && <span className="home-confidence">Confidence: {confidence(rca.analysis)}</span>}</div>{rcaBusy ? <div className="home-rca-loading"><span className="home-spinner"/>Building RCA from Davis evidence, logs, snapshots and recurrence…</div> : rcaError ? <div className="home-rca-error">{rcaError}</div> : rca ? <div className="home-rca-content"><div className="home-root"><span>ROOT-CAUSE ENTITY</span><strong className={rca.nativeRootCauseEntity ? 'found' : 'not-found'}>{rca.nativeRootCauseEntity ?? 'Not identified by Davis'}</strong><p>{rca.nativeRootCauseEntity ? 'Davis exposed a definitive root-cause entity in the problem evidence.' : 'Davis did not expose a definitive root-cause entity. The strongest evidence below is an assessment, not a confirmed root cause.'}</p></div><div className="home-finding"><span>EXECUTIVE FINDING</span><p>{section(rca.analysis, 'Executive Summary') || 'No executive summary returned.'}</p></div><div className="home-mini-grid"><div><span>RECURRENCE</span><strong>{rca.occurrenceCount.toLocaleString()}</strong><small>matching · 30d</small></div><div><span>SCOPE</span><strong>{(rca.managementZones ?? []).join(', ') || 'Not derived'}</strong><small>Management Zone</small></div><div><span>EVENTS</span><strong>{rca.evidenceSummary.correlatedEvents}</strong><small>correlated Davis events</small></div><div><span>LOGS</span><strong>{rca.evidenceSummary.incidentLogs}</strong><small>incident-window logs</small></div></div><div className="home-rca-actions"><button type="button" onClick={() => navigate(`/rca?problemId=${encodeURIComponent(rca.problemId)}`)}>View full 12-section RCA</button><button type="button" onClick={() => downloadCioRcaPdf(rca)}>↓ Download CIO-ready PDF</button></div></div> : null}</section>
  <div className="home-detail-grid"><div><div className="home-detail-title">Impact assessment</div><div className="home-detail-box">{detail.problemAnalysis?.impactSummary ?? `Impact level: ${detail.impactLevel ?? 'not available'}.`}{impacts.length > 0 && <ul>{impacts.slice(0, 8).map((impact, index) => <li key={`${impact.impactType ?? 'impact'}-${index}`}>{impact.impactType ?? 'Impact'}{impact.impactedEntity?.name ? ` — ${impact.impactedEntity.name}` : ''}{impact.estimatedAffectedUsers ? ` — ${impact.estimatedAffectedUsers} users` : ''}</li>)}</ul>}</div></div><div><div className="home-detail-title">Davis evidence</div><div className="home-detail-box"><ul>{(detail.evidenceDetails?.details ?? []).slice(0, 8).map((evidence, index) => <li key={`${evidence.displayName ?? 'evidence'}-${index}`}><b>{evidence.displayName ?? evidence.evidenceType ?? 'Evidence'}</b>{evidence.entity?.name ? ` — ${evidence.entity.name}` : ''}{evidence.rootCauseRelevant ? ' · root-cause relevant' : ''}</li>)}{!detail.evidenceDetails?.details?.length && <li>No detailed evidence returned.</li>}</ul></div></div></div></div></section></div>}
  </div></main></Flex>;
};
