import { problemsClient } from '@dynatrace-sdk/client-classic-environment-v2';
import { publicClient } from '@dynatrace-sdk/client-davis-copilot';

type Row = Record<string, unknown>;
interface AnalyzePayload { problemId: string; }

const text = (value: unknown): string => {
  if (value == null) return '';
  if (typeof value === 'string') return value;
  if (typeof value === 'number' || typeof value === 'boolean' || typeof value === 'bigint') return String(value);
  if (Array.isArray(value)) return value.map(text).filter(Boolean).join('; ');
  if (typeof value === 'object') {
    const record = value as Row;
    for (const key of ['name', 'displayName', 'entityName', 'id', 'entityId', 'value']) {
      const found = text(record[key]);
      if (found) return found;
    }
  }
  return '';
};

const duration = (start: string, end: string): string => {
  const a = new Date(start).getTime();
  const b = end ? new Date(end).getTime() : Date.now();
  if (!Number.isFinite(a) || !Number.isFinite(b)) return '—';
  const mins = Math.max(0, b - a) / 60000;
  return mins < 60 ? `${mins.toFixed(1)} min` : mins < 1440 ? `${(mins / 60).toFixed(1)} h` : `${(mins / 1440).toFixed(1)} d`;
};

function extractAssistText(value: unknown): string {
  if (typeof value === 'string') return value.trim();
  if (Array.isArray(value)) return value.map(extractAssistText).filter(Boolean).join('\n').trim();
  if (!value || typeof value !== 'object') return '';
  const record = value as Row;
  for (const key of ['text', 'answer', 'content', 'message']) {
    const found = extractAssistText(record[key]);
    if (found) return found;
  }
  if (Array.isArray(record.tokens)) return record.tokens.map(text).join('').trim();
  return '';
}

function fallback(id: string, problem: Row, reason: string): string {
  return `## Executive Summary\nProblem ${id} RCA could not be generated by Dynatrace Assist.\n\n## Incident Overview\nTitle: ${text(problem['event.name']) || 'Dynatrace Problem'}\nStatus: ${text(problem['event.status']) || 'Not available'}\nSeverity: ${text(problem['event.severity']) || 'Not available'}\nStarted: ${text(problem['event.start']) || 'Not available'}\n\n## Root Cause Assessment\nNot proven by available evidence.\n\n## Technical Root-Cause Chain\nNot proven by available evidence.\n\n## Incident Timeline\nNot available.\n\n## Past Occurrences & Recurrence Pattern\nNot available.\n\n## Impact Assessment\nImpact level: ${text(problem['dt.davis.impact_level']) || 'Not available'}.\n\n## Immediate Remediation Plan\nValidate the incident in Dynatrace and correlate the affected service with the Davis evidence.\n\n## Permanent / Preventive Actions\nNot proposed until the causal signal is confirmed.\n\n## Monitoring & Alerting Recommendations\nMonitor the affected service, response time, errors and dependency health.\n\n## Validation Checklist\nConfirm root cause, remediation and recovery.\n\n## RCA Confidence & Evidence Gaps\nLow — Davis Assist did not return an RCA.\n\nDavis Assist status: ${reason}`;
}

async function runAssist(id: string, problem: Row): Promise<{ analysis: string; status: string; fallback: boolean }> {
  // Keep this request intentionally close to the proven real-Davis-Assist interaction.
  // Do not add DQL, logs, snapshots, listAvailableSkills, acceptType or large body.text here.
  const prompt = `Analyze Dynatrace Problem ${id} and create a customer-ready incident RCA. Use the telemetry and Davis analysis available for this problem. Provide: Executive Summary, Incident Overview, Root Cause Assessment, Technical Root-Cause Chain, Incident Timeline, Impact Assessment, Immediate Remediation Plan, Permanent / Preventive Actions, Monitoring & Alerting Recommendations, Validation Checklist, and RCA Confidence & Evidence Gaps. Do not invent facts; clearly mark anything not proven by available evidence.`;

  try {
    const response = await Promise.race([
      publicClient.recommenderConversation({
        body: { text: prompt },
      }),
      new Promise<never>((_, reject) => setTimeout(() => reject(new Error('Dynatrace Assist request exceeded 45 seconds.')), 45000)),
    ]);

    if (Array.isArray(response)) {
      return { analysis: fallback(id, problem, 'unexpected streaming response'), status: 'unexpected streaming response', fallback: true };
    }

    const result = response as { status?: string };
    if (result.status === 'FAILED') {
      return { analysis: fallback(id, problem, 'FAILED'), status: 'FAILED', fallback: true };
    }

    const answer = extractAssistText(response);
    if (!answer) {
      return { analysis: fallback(id, problem, 'empty response'), status: 'empty response', fallback: true };
    }
    return { analysis: answer, status: result.status || 'SUCCESSFUL', fallback: false };
  } catch (error) {
    const reason = error instanceof Error ? error.message : 'Unknown Dynatrace Assist error.';
    return { analysis: fallback(id, problem, reason), status: reason, fallback: true };
  }
}

export default async function (payload: AnalyzePayload) {
  if (!payload?.problemId) throw new Error('problemId is required');
  if (!/^P-\d+$/.test(payload.problemId)) throw new Error('A valid Dynatrace Problem ID such as P-260948426 is required.');

  // This native call is already proven to work in the Incident Intelligence popup.
  const problem = await problemsClient.getProblem({
    problemId: payload.problemId,
    fields: 'evidenceDetails,impactAnalysis,recentComments',
  }) as unknown as Row;

  const result = await runAssist(payload.problemId, problem);
  const root = text(problem.rootCauseEntity) || text(problem['root_cause_entity_id']) || text(problem['root_cause.smartscape_entity']);
  const impact = text(problem.impactLevel) || text(problem['dt.davis.impact_level']);
  const start = text(problem.startTime) || text(problem['event.start']);
  const end = text(problem.endTime) || text(problem['event.end']);

  return {
    problemId: payload.problemId,
    analysis: result.analysis,
    generatedAt: new Date().toISOString(),
    nativeRootCauseEntity: root || null,
    definitiveRootCause: Boolean(root),
    assistFallback: result.fallback,
    assistStatus: result.status,
    recurrenceWindow: '30d',
    managementZones: [],
    occurrenceCount: 0,
    occurrences: [],
    problemFacts: {
      title: text(problem.title) || text(problem['event.name']) || 'Dynatrace Problem',
      status: text(problem.status) || text(problem['event.status']) || 'Not available',
      severity: text(problem.severity) || text(problem['event.severity']) || 'Not available',
      start,
      end,
      duration: duration(start, end),
      impactLevel: impact || 'Not available',
      affectedUsers: text(problem.affectedUsers) || text(problem['dt.davis.affected_users_count']),
      affectedEntities: text(problem.affectedEntities) || text(problem.affected_entity_names) || text(problem.affected_entity_ids),
    },
    evidenceSummary: {
      correlatedEvents: 0,
      incidentLogs: 0,
      historicalOccurrences: 0,
      timelineSnapshots: 0,
    },
  };
}
